/**
 * @file tpl_external_interrupts.c
 *
 * @section desc File description
 *
 * External interrupts init and acknowledge functions for lab1
 * Automatically generated by goil on Tue Oct  4 17:15:20 2016
 * from root OIL file lab2.oil
 *
 * @section copyright Copyright
 *
 * Trampoline OS
 *
 * Trampoline is copyright (c) IRCCyN 2005-2007
 * Trampoline is protected by the French intellectual property law.
 *
 * This software is distributed under the Lesser GNU Public Licence
 *
 * @section infos File informations
 *
 * $Date$
 * $Rev$
 * $Author$
 * $URL$
 */

#include "tpl_machine.h"


/*
 * External Interrupts initialization for the STM32F407 Microcontroller
 *
 * Interrupt vectors are EXTI0_IRQ, EXTI1_IRQ, EXTI2_IRQ, EXTI3_IRQ, EXTI4_IRQ
 * EXTI9_9_IRQ and EXTI15_10_IRQ
 *
 * Inits are done according to the source(s) pin(s) selected for an interrupt
 * vector corresponding to an or a set of interrupt(s) line(s)
 */
#define OS_START_SEC_CODE
#include "tpl_memmap.h"

FUNC(void, OS_CODE) tpl_init_external_interrupts()
{
}

#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

/* End of file tpl_external_interrupts.c */

